include:
  project: edalex-group/development/oeq/openequella-ci
  file: build/main.yml
  # TODO: revert to `main` once the corresponding openequella-ci MR is merged.
  ref: test/scalatest-consolidation
