version: 0.2

env:
  variables:
    KALTURA_BRANCH: master
    AUTOTEST_CONFIG: "autotest/codebuild.conf"
    EQ_EXIFTOOL_PATH: "/usr/bin/exiftool"
phases:
  pre_build:
    commands:
      - env | sort | grep -vi -e key -e secret -e password
      - setupBuild
      - . $NVM_DIR/nvm.sh && nvm install # version from nvmrc
      - npm config set unsafe-perm true
  install:
    commands:
      - service postgresql start
  build:
    commands:
      - (npm ci && cd Source/Plugins/Core/com.equella.core/js && npm ci)
      - (npm run check:ts && npm run check:ts-types-source && check:license)
      - (cd Source/Plugins/Core/com.equella.core/js && npm test)
      - sbt -no-colors -Dconfig.file=${HOME}/build.conf test installerZip writeLanguagePack writeScriptingJavadoc
      - sbt -mem 2048 -no-colors "project autotest" installEquella startEquella configureInstall setupForTests Tests/test Tests/Serial/test OldTests/test coverageReport
      - (cd import-export-tool && ./gradlew build)
  post_build:
    commands:
      - publishBuildResults
cache:
  paths:
    - "/root/.ivy2/**/*"
    - "/root/.npm/**/*"
    - "/root/.sbt/**/*"
