version: 0.2

env:
  variables:
    KALTURA_BRANCH: master
phases:
  pre_build:
    commands:
      - env
      - yarn global add psc-package
      - setupBuild
  build:
    commands:
      - sbt -no-colors -Dconfig.file=${HOME}/build.conf test installerZip writeLanguagePack
  post_build:
    commands:
      - publishBuild
      - echo "Finished"
cache:
  paths:
    - '/root/.ivy2/**/*'
    - '/root/.npm/**/*'
    - '/root/.sbt/**/*'
    
