/*
 * Copyright 2017 Apereo
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.10 at 02:09:22 PM EST 
//


package com.tle.web.lti.imsx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for imsx_POXHeader.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="imsx_POXHeader.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.imsglobal.org/services/ltiv1p1/xsd/imsoms_v1p0}imsx_POXRequestHeaderInfo"/>
 *         &lt;element ref="{http://www.imsglobal.org/services/ltiv1p1/xsd/imsoms_v1p0}imsx_POXResponseHeaderInfo"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "imsx_POXHeader.Type", propOrder = {
    "imsxPOXRequestHeaderInfo",
    "imsxPOXResponseHeaderInfo"
})
public class ImsxPOXHeaderType {

    @XmlElement(name = "imsx_POXRequestHeaderInfo")
    protected ImsxRequestHeaderInfoType imsxPOXRequestHeaderInfo;
    @XmlElement(name = "imsx_POXResponseHeaderInfo")
    protected ImsxResponseHeaderInfoType imsxPOXResponseHeaderInfo;

    /**
     * Gets the value of the imsxPOXRequestHeaderInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ImsxRequestHeaderInfoType }
     *     
     */
    public ImsxRequestHeaderInfoType getImsxPOXRequestHeaderInfo() {
        return imsxPOXRequestHeaderInfo;
    }

    /**
     * Sets the value of the imsxPOXRequestHeaderInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImsxRequestHeaderInfoType }
     *     
     */
    public void setImsxPOXRequestHeaderInfo(ImsxRequestHeaderInfoType value) {
        this.imsxPOXRequestHeaderInfo = value;
    }

    /**
     * Gets the value of the imsxPOXResponseHeaderInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ImsxResponseHeaderInfoType }
     *     
     */
    public ImsxResponseHeaderInfoType getImsxPOXResponseHeaderInfo() {
        return imsxPOXResponseHeaderInfo;
    }

    /**
     * Sets the value of the imsxPOXResponseHeaderInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImsxResponseHeaderInfoType }
     *     
     */
    public void setImsxPOXResponseHeaderInfo(ImsxResponseHeaderInfoType value) {
        this.imsxPOXResponseHeaderInfo = value;
    }

}
