/*
 * Copyright 2017 Apereo
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.10 at 02:09:22 PM EST 
//


package com.tle.web.lti.imsx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for imsx_POXBody.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="imsx_POXBody.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.imsglobal.org/services/ltiv1p1/xsd/imsoms_v1p0}deleteResultRequest"/>
 *         &lt;element ref="{http://www.imsglobal.org/services/ltiv1p1/xsd/imsoms_v1p0}deleteResultResponse"/>
 *         &lt;element ref="{http://www.imsglobal.org/services/ltiv1p1/xsd/imsoms_v1p0}readResultRequest"/>
 *         &lt;element ref="{http://www.imsglobal.org/services/ltiv1p1/xsd/imsoms_v1p0}readResultResponse"/>
 *         &lt;element ref="{http://www.imsglobal.org/services/ltiv1p1/xsd/imsoms_v1p0}replaceResultRequest"/>
 *         &lt;element ref="{http://www.imsglobal.org/services/ltiv1p1/xsd/imsoms_v1p0}replaceResultResponse"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "imsx_POXBody.Type", propOrder = {
    "deleteResultRequest",
    "deleteResultResponse",
    "readResultRequest",
    "readResultResponse",
    "replaceResultRequest",
    "replaceResultResponse"
})
public class ImsxPOXBodyType {

    protected DeleteResultRequest deleteResultRequest;
    protected DeleteResultResponse deleteResultResponse;
    protected ReadResultRequest readResultRequest;
    protected ReadResultResponse readResultResponse;
    protected ReplaceResultRequest replaceResultRequest;
    protected ReplaceResultResponse replaceResultResponse;

    /**
     * Gets the value of the deleteResultRequest property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteResultRequest }
     *     
     */
    public DeleteResultRequest getDeleteResultRequest() {
        return deleteResultRequest;
    }

    /**
     * Sets the value of the deleteResultRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteResultRequest }
     *     
     */
    public void setDeleteResultRequest(DeleteResultRequest value) {
        this.deleteResultRequest = value;
    }

    /**
     * Gets the value of the deleteResultResponse property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteResultResponse }
     *     
     */
    public DeleteResultResponse getDeleteResultResponse() {
        return deleteResultResponse;
    }

    /**
     * Sets the value of the deleteResultResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteResultResponse }
     *     
     */
    public void setDeleteResultResponse(DeleteResultResponse value) {
        this.deleteResultResponse = value;
    }

    /**
     * Gets the value of the readResultRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ReadResultRequest }
     *     
     */
    public ReadResultRequest getReadResultRequest() {
        return readResultRequest;
    }

    /**
     * Sets the value of the readResultRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReadResultRequest }
     *     
     */
    public void setReadResultRequest(ReadResultRequest value) {
        this.readResultRequest = value;
    }

    /**
     * Gets the value of the readResultResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ReadResultResponse }
     *     
     */
    public ReadResultResponse getReadResultResponse() {
        return readResultResponse;
    }

    /**
     * Sets the value of the readResultResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReadResultResponse }
     *     
     */
    public void setReadResultResponse(ReadResultResponse value) {
        this.readResultResponse = value;
    }

    /**
     * Gets the value of the replaceResultRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ReplaceResultRequest }
     *     
     */
    public ReplaceResultRequest getReplaceResultRequest() {
        return replaceResultRequest;
    }

    /**
     * Sets the value of the replaceResultRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplaceResultRequest }
     *     
     */
    public void setReplaceResultRequest(ReplaceResultRequest value) {
        this.replaceResultRequest = value;
    }

    /**
     * Gets the value of the replaceResultResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ReplaceResultResponse }
     *     
     */
    public ReplaceResultResponse getReplaceResultResponse() {
        return replaceResultResponse;
    }

    /**
     * Sets the value of the replaceResultResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplaceResultResponse }
     *     
     */
    public void setReplaceResultResponse(ReplaceResultResponse value) {
        this.replaceResultResponse = value;
    }

}
