//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.10 at 02:09:22 PM EST 
//


package com.tle.web.lti.imsx;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for imsx_CodeMajor.Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="imsx_CodeMajor.Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="success"/>
 *     &lt;enumeration value="processing"/>
 *     &lt;enumeration value="failure"/>
 *     &lt;enumeration value="unsupported"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "imsx_CodeMajor.Type")
@XmlEnum
public enum ImsxCodeMajorType {

    @XmlEnumValue("success")
    SUCCESS("success"),
    @XmlEnumValue("processing")
    PROCESSING("processing"),
    @XmlEnumValue("failure")
    FAILURE("failure"),
    @XmlEnumValue("unsupported")
    UNSUPPORTED("unsupported");
    private final String value;

    ImsxCodeMajorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ImsxCodeMajorType fromValue(String v) {
        for (ImsxCodeMajorType c: ImsxCodeMajorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
