//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.10 at 02:09:22 PM EST 
//


package com.tle.web.lti.imsx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The Result complexType is the container for a Result. Each Result identifies the Person to whom the result is assigned and the set of attributes for the result value.
 *             
 * 
 * <p>Java class for Result.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Result.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.imsglobal.org/services/ltiv1p1/xsd/imsoms_v1p0}resultScore" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Result.Type", propOrder = {
    "resultScore"
})
public class ResultType {

    protected TextType resultScore;

    /**
     * Gets the value of the resultScore property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getResultScore() {
        return resultScore;
    }

    /**
     * Sets the value of the resultScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setResultScore(TextType value) {
        this.resultScore = value;
    }

}
