package com.tle.common.security;

public enum Privilege
{
	CREATE_ITEM,
	EDIT_ITEM,
	VIEW_ITEM,
	CLONE_ITEM,
	MOVE_ITEM,
	COMMENT_CREATE_ITEM,
	COMMENT_DELETE_ITEM,
	COMMENT_VIEW_ITEM,
	DISCOVER_ITEM,
	ARCHIVE_ITEM,
	MANAGE_WORKFLOW,
	VIEW_ACTIVATION_ITEM,
	VIEW_VIEWCOUNT,
}
