/bin/bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<- INIT_SQL
    CREATE DATABASE $OEQ_DATABASE_NAME;
    CREATE USER $OEQ_DATABASE_USERNAME;
    ALTER USER $OEQ_DATABASE_USERNAME PASSWORD '$OEQ_DATABASE_PASSWORD';
INIT_SQL
