/*
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0, (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Chip, Tooltip } from "@material-ui/core";
import { AutocompleteGetTagProps } from "@material-ui/lab";
import * as React from "react";

export interface TooltipChipProps {
  /**
   * Chip's title
   */
  title: string;
  /**
   * Chip's ID
   */
  id?: string;
  /**
   * Chip's maximum width.
   */
  maxWidth?: number | string;
  /**
   * Additional Props passed to MUI Chip, which is generated by MUI Autocomplete.
   * @see AutocompleteGetTagProps
   */
  tagProps?: ReturnType<AutocompleteGetTagProps>;
}

/**
 * Provide a Chip wrapped by a Tooltip. This component is typically used with MUI Autocomplete.
 */
export const TooltipChip = ({
  title,
  id,
  tagProps,
  maxWidth,
}: TooltipChipProps) => (
  <Tooltip title={title}>
    <Chip id={id} label={title} style={{ maxWidth: maxWidth }} {...tagProps} />
  </Tooltip>
);
