schema {
  query: Queries
  mutation: Mutations
}

"A date-time without a time-zone in the ISO-8601 calendar system in the format of 1970-01-01T00:00:00"
scalar LocalDateTime

scalar Long

scalar Unit

"A configuration of a transform which controls how licensed materials are cited in openEQUELLA."
input CitationInput {
  "Name for the citation"
  name: String!
  "Name of the XSLT file for citation - can be downloaded from the server"
  transformation: String!
}

"The details for an entity that is now ready to be edited, or the updated details for that entity after editing."
input EditableEntityMetadataSchemaInput {
  "Base entity being edited"
  entity: MetadataSchemaInput!
  "The ID of the staging area for this entity. This is used to store files before they are committed."
  stagingId: String!
  "The version of openEQUELLA this entity is being edited against. This is used to ensure that edits are applied to the correct version."
  version: String
  "A list of access control entries, each specifying a privilege granted to a user or group, along with whether it is overridden or granted."
  targetList: [TargetListEntryInput!]!
}

"Common details for entities, including identifiers, ownership, timestamps, and additional attributes."
input EntityDetailsInput {
  "Unique identifier for this entity."
  id: Long!
  "Universally unique identifier for this entity, used for referencing across different entities."
  uuid: String!
  "Owner of this entity, typically the user who created it."
  owner: String!
  "Timestamp for when this entity was created - only valid when starting an edit on an existing entity."
  dateCreated: LocalDateTime
  "Timestamp for when this entity was last modified - only valid when starting an edit on an existing entity."
  dateModified: LocalDateTime
  "Language bundle for the _name_ of this entity, used for internationalization."
  nameBundle: LanguageBundleInput
  "Language bundle for the _description_ of this entity, used for internationalization."
  descriptionBundle: LanguageBundleInput
  "A map of additional attributes for this entity, allowing for flexible metadata storage."
  attributes: [KVStringStringInput!]!
  "Indicates whether this entity is disabled, affecting its visibility and usability."
  disabled: Boolean!
}

"A key-value pair of String and String"
input KVStringStringInput {
  "Key"
  key: String!
  "Value"
  value: String!
}

"A bundle of language strings, each representing a translation for a specific locale."
input LanguageBundleInput {
  "Unique identifier for this language bundle."
  id: Long!
  "List of language strings in this bundle."
  strings: [LanguageStringInput!]!
}

"A single translation of a piece of text for a specific locale."
input LanguageStringInput {
  "Unique identifier for this language string."
  id: Long!
  "Priority of this language string, with lower numbers indicating higher priority."
  priority: Int!
  "Locale code for this language string, e.g., 'en' for English."
  locale: String!
  "The translated text for this locale."
  text: String!
}

"A metadata schema, which defines the structure and transforms for metadata items in openEQUELLA."
input MetadataSchemaInput {
  "Details of the metadata schema, including UUID and owner"
  details: EntityDetailsInput!
  "Transforms applied when exporting this schema between repositories"
  exportTransforms: [MetadataSchemaTransformInput!]!
  "Transforms applied when importing this schema between repositories"
  importTransforms: [MetadataSchemaTransformInput!]!
  "Path to the name attribute in the schema"
  itemNamePath: String!
  "Path to the description attribute in the schema"
  itemDescriptionPath: String!
  "XML definition of the schema"
  definition: String!
  "List of citations associated with this schema"
  citations: [CitationInput!]!
}

"A schema transform that defines how metadata is transformed during export or import operations with external systems."
input MetadataSchemaTransformInput {
  "Filename of the schema transform stored on the server - managed via staging area"
  filename: String!
  "Type of the schema transform, e.g., OAI_Identity, HARVESTER, OAI_DC"
  schemaType: String!
}

input TargetListEntryInput {
  "Whether the privilege is granted or revoked"
  granted: Boolean!
  "Has precedence over other actions in the list"
  overridden: Boolean!
  "The privilege being granted or revoked, e.g., 'VIEW_ITEM', 'EDIT_SCHEMA', etc."
  privilege: String!
  "The user, group or other entity this applies to. Expecting values like '*', 'U:<username>', 'G:<groupname>' etc."
  who: String!
  "An optional postfix for the entry, used for additional context or information - defaults to empty string"
  postfix: String!
}

type BaseEntityReference {
  "The database ID of the entity"
  id: Long!
  "The UUID of the entity"
  uuid: String!
  "The language bundle ID of the entity"
  bundleId: Long!
  "The owner of the entity"
  owner: String!
  "Whether this entity is a collection"
  forCollection: Boolean!
}

"A configuration of a transform which controls how licensed materials are cited in openEQUELLA."
type Citation {
  "Name for the citation"
  name: String!
  "Name of the XSLT file for citation - can be downloaded from the server"
  transformation: String!
}

"The details for an entity that is now ready to be edited, or the updated details for that entity after editing."
type EditableEntityMetadataSchema {
  "Base entity being edited"
  entity: MetadataSchema!
  "The ID of the staging area for this entity. This is used to store files before they are committed."
  stagingId: String!
  "The version of openEQUELLA this entity is being edited against. This is used to ensure that edits are applied to the correct version."
  version: String
  "A list of access control entries, each specifying a privilege granted to a user or group, along with whether it is overridden or granted."
  targetList: [TargetListEntry!]!
}

"A skeleton for creating a new editable entity, containing essential metadata such as UUID, owner, and staging ID."
type EditableEntitySkeleton {
  "Unique identifier for the new entity"
  uuid: String!
  "Owner of the new entity, typically the user who is creating it"
  owner: String!
  "Staging ID for the new entity, used to store files before they are committed"
  stagingId: String!
}

"Common details for entities, including identifiers, ownership, timestamps, and additional attributes."
type EntityDetails {
  "Unique identifier for this entity."
  id: Long!
  "Universally unique identifier for this entity, used for referencing across different entities."
  uuid: String!
  "Owner of this entity, typically the user who created it."
  owner: String!
  "Timestamp for when this entity was created - only valid when starting an edit on an existing entity."
  dateCreated: LocalDateTime
  "Timestamp for when this entity was last modified - only valid when starting an edit on an existing entity."
  dateModified: LocalDateTime
  "Language bundle for the _name_ of this entity, used for internationalization."
  nameBundle: LanguageBundle
  "Language bundle for the _description_ of this entity, used for internationalization."
  descriptionBundle: LanguageBundle
  "A map of additional attributes for this entity, allowing for flexible metadata storage."
  attributes: [KVStringString!]!
  "Indicates whether this entity is disabled, affecting its visibility and usability."
  disabled: Boolean!
}

type Group {
  "The unique identifier for the group - typically a UUID"
  uniqueId: String!
  "The name of the group"
  name: String!
  "The description for the group"
  description: String
  "The unique identifier of the parent group, or null if this is a top-level group"
  parentId: String
  "Whether this group has sub-groups"
  hasGroups: Boolean!
  "Whether this group has users"
  hasUsers: Boolean!
}

"A Connection object paging through Groups as per the GraphQL Cursor Connections Specification"
type GroupConnection {
  pageInfo: PageInfo!
  edges: [GroupEdge!]!
}

"An Edge object for Groups as per the GraphQL Cursor Connections Specification"
type GroupEdge {
  cursor: String!
  node: Group!
}

type InternalGroupMutations {
  "Create a new group"
  create("The name of the group to create" name: String!, "The unique ID of the parent group to create the new group under - or none for the root" parentId: String): Group
  "Delete a group by its unique ID"
  delete("The unique ID of the group to delete" uniqueId: String!, "Whether to delete all children of the group, or move them to the parent of the group being deleted" deleteChildren: Boolean!): Unit
  "Update a group by its unique ID - can also be used to move group within the hierarchy by changing the parent ID"
  update("The unique ID of the group to update" uniqueId: String!, "The new name of the group" name: String, "The new description for the group" description: String, "The new parent ID of the group" parentId: String, "The updated list of users in the group - replacing what was previously there." users: [String!]): Group
}

type InternalGroupQueries {
  "Retrieve a group by its unique ID"
  byId("The unique ID of the group to retrieve" uniqueId: String!): Group
  "Retrieve a group by its name"
  byName("The name of the group to retrieve" name: String!): Group
  "List all groups at a specific level in the hierarchy determined by the parent ID - or none for the root."
  list("The unique ID of the parent group to list groups for - or none for the root" parentId: String, "Pagination - how many items to return from the start of the possible list of items" first: Int, "Pagination - how many items to return from the end of the possible list of items" last: Int, "Pagination - the cursor for a item before which all items should be returned" before: String, "Pagination - the cursor for a item after which all items should be returned" after: String): GroupConnection
  "List multiple groups by their unique IDs, invalid IDs will be ignored"
  listByIds("The unique IDs of the groups to retrieve" uniqueIds: [String!]!, "Pagination - how many items to return from the start of the possible list of items" first: Int, "Pagination - how many items to return from the end of the possible list of items" last: Int, "Pagination - the cursor for a item before which all items should be returned" before: String, "Pagination - the cursor for a item after which all items should be returned" after: String): GroupConnection
  "Search for groups anywhere within the hierarchy by name (wildcard search)"
  search("The query string to search for groups by (server will surround with wildcard)" query: String!, "Pagination - how many items to return from the start of the possible list of items" first: Int, "Pagination - how many items to return from the end of the possible list of items" last: Int, "Pagination - the cursor for a item before which all items should be returned" before: String, "Pagination - the cursor for a item after which all items should be returned" after: String): GroupConnection
  "List user ids for all users in the specified group"
  users("The unique ID of the group to list users for" uniqueId: String!, "Pagination - how many items to return from the start of the possible list of items" first: Int, "Pagination - how many items to return from the end of the possible list of items" last: Int, "Pagination - the cursor for a item before which all items should be returned" before: String, "Pagination - the cursor for a item after which all items should be returned" after: String): StringConnection
}

type InternalUserMutations {
  "Create a new internal user"
  create("Username of the user to create which they'll use for authentication - must be unique" username: String!, "Email address of the user" email: String, "First name of the user" firstName: String!, "Last name of the user" lastName: String!, "Password of the user - will be hashed on store" password: String!): User
  "Update an existing internal user"
  update("ID of existing user to update - used to find target user" id: String!, "New username of the user - should be unique" username: String, "New email address of the user" email: String, "New first name of the user" firstName: String, "New last name of the user" lastName: String, "New password of the user - will be hashed on store" password: String): User
  "Delete an existing internal user"
  delete("The unique ID of the user to delete" id: String!): Unit
}

type InternalUserQueries {
  "List all internal users, optionally filtered by a query"
  list("A string to filter users by" query: String, "Pagination - how many items to return from the start of the possible list of items" first: Int, "Pagination - how many items to return from the end of the possible list of items" last: Int, "Pagination - the cursor for a item before which all items should be returned" before: String, "Pagination - the cursor for a item after which all items should be returned" after: String): UserConnection
  "Retrieve details of a user based on username"
  byUsername("Username of the user to retrieve" username: String!): User
  "Retrieve details of a user based on unique ID"
  byId("Unique ID of the user to retrieve" id: String!): User
}

"A key-value pair of String and String"
type KVStringString {
  "Key"
  key: String!
  "Value"
  value: String!
}

"A bundle of language strings, each representing a translation for a specific locale."
type LanguageBundle {
  "Unique identifier for this language bundle."
  id: Long!
  "List of language strings in this bundle."
  strings: [LanguageString!]!
}

"A single translation of a piece of text for a specific locale."
type LanguageString {
  "Unique identifier for this language string."
  id: Long!
  "Priority of this language string, with lower numbers indicating higher priority."
  priority: Int!
  "Locale code for this language string, e.g., 'en' for English."
  locale: String!
  "The translated text for this locale."
  text: String!
}

"A metadata schema, which defines the structure and transforms for metadata items in openEQUELLA."
type MetadataSchema {
  "Details of the metadata schema, including UUID and owner"
  details: EntityDetails!
  "Transforms applied when exporting this schema between repositories"
  exportTransforms: [MetadataSchemaTransform!]!
  "Transforms applied when importing this schema between repositories"
  importTransforms: [MetadataSchemaTransform!]!
  "Path to the name attribute in the schema"
  itemNamePath: String!
  "Path to the description attribute in the schema"
  itemDescriptionPath: String!
  "XML definition of the schema"
  definition: String!
  "List of citations associated with this schema"
  citations: [Citation!]!
}

type MetadataSchemaMutations {
  "Start editing an existing metadata schema. Expected that it will be followed by a stopEdit or cancelEdit operation."
  startEdit("ID of the metadata schema to edit, or none to create a new one" id: Long!): EditableEntityMetadataSchema!
  "Start creating a new metadata schema. Typically followed by an add operation with details for new schema."
  startCreate: EditableEntitySkeleton!
  "Cancel editing a metadata schema - discarding any changes made and unlocking the schema."
  cancelEdit("ID of the metadata schema edit session to cancel" id: Long!, "Whether to force cancel the edit session, if true, removes the lock regardless of which session owns it (forced unlock); if false, only removes the lock if the current session owns it. Defaults to false if not provided." force: Boolean): Unit
  "Add a new metadata schema - typically after a startCreate operation, with details for the new schema."
  add("Details of the metadata schema to add" details: EditableEntityMetadataSchemaInput!, "Whether the newly added schema should be locked for editing after creation" lockAfterwards: Boolean!): BaseEntityReference
  "Delete a metadata schema - with consideration to references controllable by args."
  delete("ID of the metadata schema to delete" id: Long!, "Whether to check for referencing entities before deletion, if true, the deletion will only proceed if there are no referencing entities; if false, will attempt to delete the schema regardless of references which may fail. Defaults to true if not provided." checkReferences: Boolean): Unit
}

type MetadataSchemaQueries {
  "List all metadata schemas"
  list: [BaseEntityReference!]!
  "Export a metadata schema, returning a base64 encoded zip file"
  export("ID of the metadata schema to export" id: Long!, "Whether to include security information in the export" withSecurity: Boolean!): String
  "Get the metadata schema ID for a given UUID"
  idForUuid(value: String!): Long
  "Get a metadata schema by ID"
  byId("ID of the metadata schema" id: Long!): MetadataSchema
  "Get the uses of a metadata schema by ID"
  uses("ID of the metadata schema" id: Long!): [BaseEntityReference!]!
  "Get the types of schema import transformations for a metadata schema by ID"
  importTypes("ID of the metadata schema" id: Long!): [String!]!
  "Check if a metadata schema has an referencing entities"
  hasReferences("ID of the metadata schema" id: Long!): Boolean!
}

"A schema transform that defines how metadata is transformed during export or import operations with external systems."
type MetadataSchemaTransform {
  "Filename of the schema transform stored on the server - managed via staging area"
  filename: String!
  "Type of the schema transform, e.g., OAI_Identity, HARVESTER, OAI_DC"
  schemaType: String!
}

type Mutations {
  "Operations for managing internal users"
  internalUsers: InternalUserMutations!
  "Operations for managing internal groups"
  internalGroups: InternalGroupMutations!
  "Operations for managing Metadata Schemas"
  metadataSchema: MetadataSchemaMutations!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Queries {
  "Queries for internal users"
  internalUsers: InternalUserQueries!
  "Queries for internal groups"
  internalGroups: InternalGroupQueries!
  "Queries for Metadata Schemas"
  metadataSchema: MetadataSchemaQueries!
}

"A Connection object paging through Strings as per the GraphQL Cursor Connections Specification"
type StringConnection {
  pageInfo: PageInfo!
  edges: [StringEdge!]!
}

"An Edge object for Strings as per the GraphQL Cursor Connections Specification"
type StringEdge {
  cursor: String!
  node: String!
}

type TargetListEntry {
  "Whether the privilege is granted or revoked"
  granted: Boolean!
  "Has precedence over other actions in the list"
  overridden: Boolean!
  "The privilege being granted or revoked, e.g., 'VIEW_ITEM', 'EDIT_SCHEMA', etc."
  privilege: String!
  "The user, group or other entity this applies to. Expecting values like '*', 'U:<username>', 'G:<groupname>' etc."
  who: String!
  "An optional postfix for the entry, used for additional context or information - defaults to empty string"
  postfix: String!
}

type User {
  "The unique identifier for the user"
  uniqueId: String!
  "The username a user authenticates with"
  username: String!
  "User's email address"
  email: String
  "User's first name"
  firstName: String!
  "User's last name"
  lastName: String!
}

"A Connection object paging through Users as per the GraphQL Cursor Connections Specification"
type UserConnection {
  pageInfo: PageInfo!
  edges: [UserEdge!]!
}

"An Edge object for Users as per the GraphQL Cursor Connections Specification"
type UserEdge {
  cursor: String!
  node: User!
}
