schema {
  query: Queries
  mutation: Mutations
}
scalar Unit

type Group {
  "The unique identifier for the group - typically a UUID"
  uniqueId: String!
  "The name of the group"
  name: String!
  "The unique identifier of the parent group, or null if this is a top-level group"
  parentId: String
  "Whether this group has sub-groups"
  hasGroups: Boolean!
  "Whether this group has users"
  hasUsers: Boolean!
}

"A Connection object paging through Groups as per the GraphQL Cursor Connections Specification"
type GroupConnection {
  pageInfo: PageInfo!
  edges: [GroupEdge!]!
}

"An Edge object for Groups as per the GraphQL Cursor Connections Specification"
type GroupEdge {
  cursor: String!
  node: Group!
}

type Mutations {
  "Create a new internal user"
  internalUserCreate("Username of the user to create which they'll use for authentication - must be unique" username: String!, "Email address of the user" email: String, "First name of the user" firstName: String!, "Last name of the user" lastName: String!, "Password of the user - will be hashed on store" password: String!): User
  "Update an existing internal user"
  internalUserUpdate("ID of existing user to update - used to find target user" id: String!, "New username of the user - should be unique" username: String, "New email address of the user" email: String, "New first name of the user" firstName: String, "New last name of the user" lastName: String, "New password of the user - will be hashed on store" password: String): User
  "Delete an existing internal user"
  internalUserDelete("The unique ID of the user to delete" id: String!): Unit
  "Create a new group"
  internalGroupCreate("The name of the group to create" name: String!, "The unique ID of the parent group to create the new group under - or none for the root" parentId: String): Group
  "Delete a group by its unique ID"
  internalGroupDelete("The unique ID of the group to delete" uniqueId: String!, "Whether to delete all children of the group, or move them to the parent of the group being deleted" deleteChildren: Boolean!): Unit
  "Update a group by its unique ID - can also be used to move group within the hierarchy by changing the parent ID"
  internalGroupUpdate("The unique ID of the group to update" uniqueId: String!, "The new name of the group" name: String, "The new parent ID of the group" parentId: String, "The updated list of users in the group - replacing what was previously there." users: [String!]): Group
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Queries {
  "List all internal users, optionally filtered by a query"
  internalUsers("A string to filter users by" query: String, "Pagination - how many items to return from the start of the possible list of items" first: Int, "Pagination - how many items to return from the end of the possible list of items" last: Int, "Pagination - the cursor for a item before which all items should be returned" before: String, "Pagination - the cursor for a item after which all items should be returned" after: String): UserConnection
  "Retrieve details of a user based on username"
  internalUserByUsername("Username of the user to retrieve" username: String!): User
  "Retrieve details of a user based on unique ID"
  internalUserById("Unique ID of the user to retrieve" id: String!): User
  "Retrieve a group by its unique ID"
  internalGroupById("The unique ID of the group to retrieve" uniqueId: String!): Group
  "Retrieve a group by its name"
  internalGroupByName("The name of the group to retrieve" name: String!): Group
  "List all groups at a specific level in the hierarchy determined by the parent ID - or none for the root."
  internalGroups("The unique ID of the parent group to list groups for - or none for the root" parentId: String, "Pagination - how many items to return from the start of the possible list of items" first: Int, "Pagination - how many items to return from the end of the possible list of items" last: Int, "Pagination - the cursor for a item before which all items should be returned" before: String, "Pagination - the cursor for a item after which all items should be returned" after: String): GroupConnection
  "Search for groups anywhere within the hierarchy by name (wildcard search)"
  internalGroupSearch("The query string to search for groups by (server will surround with wildcard)" query: String!, "Pagination - how many items to return from the start of the possible list of items" first: Int, "Pagination - how many items to return from the end of the possible list of items" last: Int, "Pagination - the cursor for a item before which all items should be returned" before: String, "Pagination - the cursor for a item after which all items should be returned" after: String): GroupConnection
  "List user ids for all users in the specified group"
  internalGroupUsers("The unique ID of the group to list users for" uniqueId: String!, "Pagination - how many items to return from the start of the possible list of items" first: Int, "Pagination - how many items to return from the end of the possible list of items" last: Int, "Pagination - the cursor for a item before which all items should be returned" before: String, "Pagination - the cursor for a item after which all items should be returned" after: String): StringConnection
}

"A Connection object paging through Strings as per the GraphQL Cursor Connections Specification"
type StringConnection {
  pageInfo: PageInfo!
  edges: [StringEdge!]!
}

"An Edge object for Strings as per the GraphQL Cursor Connections Specification"
type StringEdge {
  cursor: String!
  node: String!
}

type User {
  "The unique identifier for the user"
  uniqueId: String!
  "The username a user authenticates with"
  username: String!
  "User's email address"
  email: String
  "User's first name"
  firstName: String!
  "User's last name"
  lastName: String!
}

"A Connection object paging through Users as per the GraphQL Cursor Connections Specification"
type UserConnection {
  pageInfo: PageInfo!
  edges: [UserEdge!]!
}

"An Edge object for Users as per the GraphQL Cursor Connections Specification"
type UserEdge {
  cursor: String!
  node: User!
}