#!/usr/bin/env bash

set -euxo pipefail

MAJ_VER=$(google-chrome --version | awk '{ print $3 }' | awk -F . '{ print $1 }')
VER=$(curl --silent https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${MAJ_VER})
URL=https://chromedriver.storage.googleapis.com/$VER/chromedriver_linux64.zip
FILENAME_DL=driver.zip
FILENAME_DRIVER=chromedriver

wget -nv -O $FILENAME_DL "$URL"
unzip $FILENAME_DL
rm $FILENAME_DL
chmod a+x $FILENAME_DRIVER
mv $FILENAME_DRIVER "$1"
