#!/bin/sh

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# resolve links - $0 may be a softlink
ARG0="$0"
while [ -h "$ARG0" ]; do
  ls=`ls -ld "$ARG0"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    ARG0="$link"
  else
    ARG0="`dirname $ARG0`/$link"
  fi
done
DIRNAME="`dirname $ARG0`"
PROGRAM="`basename $ARG0`"

cd "$DIRNAME"
. "./equellaserver-config.sh"

# Setup parameters for running the jsvc
#
test ".$RUN_USER" != . && USER_FLAG="-user $RUN_USER"
# Set JAVA_HOME to working JDK or JRE
# JAVA_HOME=/opt/jdk-1.6.0.22
# If not set we'll try to guess the JAVA_HOME
# from java binary if on the PATH
#
if [ -z "$JAVA_HOME" ]; then
    JAVA_BIN="`which java 2>/dev/null || type java 2>&1`"
    test -x "$JAVA_BIN" && JAVA_HOME="`dirname $JAVA_BIN`"
    test ".$JAVA_HOME" != . && JAVA_HOME=`cd "$JAVA_HOME/.." >/dev/null; pwd`
else
    JAVA_BIN="$JAVA_HOME/bin/java"
fi

# Set EQUELLA Server HOME
test ".$EQUELLASERVER_HOME" = . && EQUELLASERVER_HOME=`cd "./../server" >/dev/null; pwd`

# Set JSVC
test ".$JSVC" = . && JSVC="./jsvc"

# Ensure that any user defined CLASSPATH variables are not used on startup,
# but allow them to be specified in setenv.sh, in rare case when it is needed.

# Set Logging configuration
test ".$LOGS_HOME" = . && LOGS_HOME=`cd "./../logs" >/dev/null; pwd`
test ".$EQUELLASERVER_OUT" = . && EQUELLASERVER_OUT="$LOGS_HOME/equellaserver.log"
JAVA_OPTS="$JAVA_OPTS $HEAP_CONFIG $JMX_CONFIG $LOGGING_MANAGER"
LOGGING_CONFIG="-Dnop"

# Set Temporary directory
test ".$EQUELLASERVER_TMP" = . && EQUELLASERVER_TMP="$EQUELLASERVER_HOME/temp"

# Set EQUELLA Server class
test ".$EQUELLA_SERVER" = . && EQUELLA_SERVER=com.tle.core.equella.runner.EQUELLAServer
# Set -pidfile
test ".$EQUELLASERVER_PID" = . && EQUELLASERVER_PID="../server/equellaserver-daemon.pid"



# ----- Execute The Requested Command -----------------------------------------
case "$1" in
    console     )
      shift
      "$JSVC" $* \
      -java-home "$JAVA_HOME" \
       $USER_FLAG \
      -pidfile "$EQUELLASERVER_PID" \
      -jvm server \
      -nodetach \
      -outfile "&1" \
      -errfile "&2" \
      -classpath "$CLASSPATH" \
      "$LOGGING_CONFIG" $JAVA_OPTS \
      -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" \
      -Djava.io.tmpdir="$EQUELLASERVER_TMP" \
      $EQUELLA_SERVER
      exit $?
    ;;
    start   )
      echo "Starting EQUELLA app server..."
      "$JSVC" \
      -java-home "$JAVA_HOME" \
       $USER_FLAG \
      -pidfile "$EQUELLASERVER_PID" \
      -jvm server \
      -outfile "$EQUELLASERVER_OUT" \
      -errfile "$EQUELLASERVER_OUT" \
      -classpath "$CLASSPATH" \
      "$LOGGING_CONFIG" $JAVA_OPTS \
      -Djava.io.tmpdir="$EQUELLASERVER_TMP" \
      $EQUELLA_SERVER
      exit $?
    ;;
    stop    )
      echo "Stopping EQUELLA app server..."
      "$JSVC" \
      -stop \
      -java-home "$JAVA_HOME" \
      -pidfile "$EQUELLASERVER_PID" \
      -classpath "$CLASSPATH" \
      -Djava.io.tmpdir="$EQUELLASERVER_TMP" \
      $EQUELLA_SERVER
      exit 0
    ;;
      restart    )
      echo "Restarting EQUELLA app server..."
      echo "Stopping EQUELLA app server..."
      "$JSVC" \
      -stop \
      -java-home "$JAVA_HOME" \
      -pidfile "$EQUELLASERVER_PID" \
      -classpath "$CLASSPATH" \
      -Djava.io.tmpdir="$EQUELLASERVER_TMP" \
      $EQUELLA_SERVER

      echo "Starting EQUELLA app server..."
      "$JSVC" \
      -java-home "$JAVA_HOME" \
       $USER_FLAG \
      -pidfile "$EQUELLASERVER_PID" \
      -jvm server \
      -outfile "$EQUELLASERVER_OUT" \
      -errfile "$EQUELLASERVER_OUT" \
      -classpath "$CLASSPATH" \
      "$LOGGING_CONFIG" $JAVA_OPTS \
      -Djava.io.tmpdir="$EQUELLASERVER_TMP" \
      $EQUELLA_SERVER
      exit $?
    ;;
    quickstatus    )
      OUTPUT=`"$JSVC" \
      -check \
      -java-home "$JAVA_HOME" \
      -pidfile "$EQUELLASERVER_PID" \
      -nodetach \
      -errfile "&1" \
      -outfile "&2" \
      -classpath "$CLASSPATH" \
      -Djava.io.tmpdir="$EQUELLASERVER_TMP" \
      $EQUELLA_SERVER`

      case "$OUTPUT" in
      *Still*)
          exit 2
          ;;
      *)
          exit 0
         ;;
      esac
    ;;
    status    )
      OUTPUT=`"$JSVC" \
      -check \
      -java-home "$JAVA_HOME" \
      -pidfile "$EQUELLASERVER_PID" \
      -nodetach \
      -errfile "&1" \
      -outfile "&2" \
      -classpath "$CLASSPATH" \
      -Djava.io.tmpdir="$EQUELLASERVER_TMP" \
      $EQUELLA_SERVER`

      case "$OUTPUT" in
      *Still*)
          echo "The EQUELLA App Server is running"
          ;;
      *)
          echo "The EQUELLA App Server is stopped"
         ;;
      esac
    ;;
    version  )
      "$JSVC" \
      -java-home "$JAVA_HOME" \
      -pidfile "$EQUELLASERVER_PID" \
      -classpath "$CLASSPATH" \
      -errfile "&2" \
      -version \
      -check \
      $EQUELLA_SERVER
      exit $?
    ;;
    *       )
      echo "Unkown command: \`$1'"
      echo "Usage: $PROGRAM ( commands ... )"
      echo "commands:"
      echo "  console           Start the EQUELLA App Server without detaching from console"
      echo "  start             Start the EQUELLA App Server"
      echo "  stop              Stop the EQUELLA App Server"
      echo "  restart           Restart the EQUELLA App Server"
      echo "  status            Check the status of the EQUELLA App Server"
      echo "  version           What version of EQUELLA Server"
      echo "                    are you running?"
      exit 1
    ;;
esac

