#!/bin/sh

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

MANAGER_MAIN="com.tle.upgrademanager.Main"

# resolve links - $0 may be a softlink
ARG0="$0"
while [ -h "$ARG0" ]; do
  ls=`ls -ld "$ARG0"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    ARG0="$link"
  else
    ARG0="`dirname $ARG0`/$link"
  fi
done
DIRNAME="`dirname $ARG0`"
PROGRAM="`basename $ARG0`"

cd "$DIRNAME"
. "./manager-config.sh"

# Setup parameters for running the jsvc
#
test ".$RUN_USER" != . && USER_FLAG="-user $RUN_USER"
# Set JAVA_HOME to working JDK or JRE
# JAVA_HOME=/opt/jdk-1.6.0.22
# If not set we'll try to guess the JAVA_HOME
# from java binary if on the PATH
#
if [ -z "$JAVA_HOME" ]; then
    JAVA_BIN="`which java 2>/dev/null || type java 2>&1`"
    test -x "$JAVA_BIN" && JAVA_HOME="`dirname $JAVA_BIN`"
    test ".$JAVA_HOME" != . && JAVA_HOME=`cd "$JAVA_HOME/.." >/dev/null; pwd`
else
    JAVA_BIN="$JAVA_HOME/bin/java"
fi

# Set Manager HOME
test ".$MANAGER_HOME" = . && MANAGER_HOME=`cd "./" >/dev/null; pwd`
test ".$EQUELLASERVER_HOME" = . && EQUELLASERVER_HOME=`cd "../server" >/dev/null; pwd`

# Set JSVC
test ".$JSVC" = . && JSVC="./jsvc"

# Set Logging configuration
test ".$LOGS_HOME" = . && LOGS_HOME=`cd "../logs" >/dev/null; pwd`
test ".$MANAGER_OUT" = . && MANAGER_OUT="$LOGS_HOME/manager.log"
test ".$MANAGER_TMP" = . && MANAGER_TMP="$EQUELLASERVER_HOME/temp"

# Set -pidfile
test ".$MANAGER_PID" = . && MANAGER_PID="$MANAGER_HOME/manager-daemon.pid"

# ----- Execute The Requested Command -----------------------------------------
case "$1" in
    console     )
      shift
      "$JSVC" $* \
      -java-home "$JAVA_HOME" \
       $USER_FLAG \
      -pidfile "$MANAGER_PID" \
      -nodetach \
      -outfile "&1" \
      -errfile "&2" \
      -classpath "$CLASSPATH" \
      $JAVA_OPTS \
      -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" \
      -Djava.io.tmpdir="$MANAGER_TMP" \
      $MANAGER_MAIN
      exit $?
    ;;
    start   )
      echo "Starting EQUELLA manager..."
      "$JSVC" \
      -java-home "$JAVA_HOME" \
      $USER_FLAG \
      -pidfile "$MANAGER_PID" \
      -outfile "$MANAGER_OUT" \
      -errfile "$MANAGER_OUT" \
      -classpath "$CLASSPATH" \
      $JAVA_OPTS \
      -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" \
      -Djava.io.tmpdir="$MANAGER_TMP" \
      $MANAGER_MAIN
      exit $?
    ;;
    stop    )
      echo "Stopping EQUELLA manager..."
      "$JSVC" \
      -stop \
      -java-home "$JAVA_HOME" \
      -pidfile "$MANAGER_PID" \
      -classpath "$CLASSPATH" \
      -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" \
      -Djava.io.tmpdir="$MANAGER_TMP" \
      $MANAGER_MAIN
      exit 0
    ;;
    restart    )
      "$JSVC" \
      -stop \
      -java-home "$JAVA_HOME" \
      -pidfile "$MANAGER_PID" \
      -classpath "$CLASSPATH" \
      -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" \
      -Djava.io.tmpdir="$MANAGER_TMP" \
      $MANAGER_MAIN

      "$JSVC" \
      -java-home "$JAVA_HOME" \
      $USER_FLAG \
      -pidfile "$MANAGER_PID" \
      -outfile "$MANAGER_OUT" \
      -errfile "$MANAGER_OUT" \
      -classpath "$CLASSPATH" \
      $JAVA_OPTS \
      -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" \
      -Djava.io.tmpdir="$MANAGER_TMP" \
      $MANAGER_MAIN
      exit $?
    ;;
    quickstatus    )
      OUTPUT=`"$JSVC" \
      -check \
      -java-home "$JAVA_HOME" \
      -pidfile "$MANAGER_PID" \
      -nodetach \
      -errfile "&1" \
      -outfile "&2" \
      -classpath "$CLASSPATH" \
      -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" \
      -Djava.io.tmpdir="$MANAGER_TMP" \
      $MANAGER_MAIN`

      case "$OUTPUT" in
      *Still*)
          exit 2
          ;;
      *)
          exit 0
         ;;
      esac
    ;;
    status    )
      OUTPUT=`"$JSVC" \
      -check \
      -java-home "$JAVA_HOME" \
      -pidfile "$MANAGER_PID" \
      -nodetach \
      -errfile "&1" \
      -outfile "&2" \
      -classpath "$CLASSPATH" \
      -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" \
      -Djava.io.tmpdir="$MANAGER_TMP" \
      $MANAGER_MAIN`

      case "$OUTPUT" in
      *Still*)
          echo "The EQUELLA manager is running"
          ;;
      *)
          echo "The EQUELLA manager is stopped"
         ;;
      esac
    ;;
    *       )
      echo "Unkown command: \`$1'"
      echo "Usage: $PROGRAM ( commands ... )"
      echo "commands:"
      echo "  console           Start the EQUELLA manager without detaching from console"
      echo "  start             Start the EQUELLA manager"
      echo "  stop              Stop the EQUELLA manager"
      echo "  restart           Restarts the EQUELLA manager"
      echo "  status            Check the status of the EQUELLA manager"
      exit 1
    ;;
esac

