/*
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0, (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.tle.integration

import com.auth0.jwt.interfaces.DecodedJWT

import java.net.URI
import scala.util.Try
import scala.jdk.CollectionConverters._
import cats.implicits._

package object lti13 {

  /**
    * Helper function for dealing with params sent the servlet endpoint. On the expectation that
    * all the params are a one-to-one value - so navigates around the need to handle the potential
    * list.
    *
    * @param params a collection of params received at one of the servlet request handlers.
    * @return a function which has wrapped over the `params` and can now be used simply with the
    *         name of an expected parameter. The function will return `None` if the param is not
    *         present
    */
  def getParam(params: Map[String, Array[String]]): String => Option[String] =
    (param: String) => params.get(param).flatMap(_.headOption)

  /**
    * Helper function for dealing with URI params, building on top of getParam. It takes the function
    * created from a call to getParam.
    *
    * @param param a function generated by `getParam`
    * @return a function which can be used to extract URI parameters from a list of params
    */
  def getUriParam(param: String => Option[String]): String => Option[URI] =
    (p: String) => param(p).flatMap(maybeUri => Try(new URI(maybeUri)).toOption)

  /**
    * From the provided decoded JWT return the specified claim which is expected to be a string.
    *
    * @param jwt   a token containing the claim
    * @param claim name of a string based claim
    * @return If available will return the string value of the claim, or `None`
    */
  def getClaim(jwt: DecodedJWT, claim: String): Option[String] =
    Option(jwt.getClaim(claim)).flatMap(c => Option(c.asString()))

  /**
    * Return the specified claim which must be present in the provided decoded JWT as a string.
    *
    * @param jwt   a token containing the claim
    * @param claim name of a string based claim
    * @return The string value of the claim, or `InvalidJWT` if the claim is absent.
    */
  def getRequiredClaim(jwt: DecodedJWT, claim: String): Either[InvalidJWT, String] =
    Option(jwt.getClaim(claim))
      .flatMap(c => Option(c.asString()))
      .toRight(InvalidJWT(s"Failed to extract $claim from JWT"))

  /**
    * For a claim where type of the value is non-textual, use this method to get the string representation
    * of the claim value.
    *
    * @param jwt a token containing the claim
    * @param claim name of a string based claim
    * @return If available will return the string representation of the claim, or `None`
    */
  def getClaimStringRepr(jwt: DecodedJWT, claim: String): Option[String] =
    Option(jwt.getClaim(claim)).flatMap(c => Option(c.toString))

  /**
    * Get value of a claim as a Map.
    *
    * @param jwt a token containing the claim
    * @param claim name of a string based claim
    * @return If transforming the value to a Map is successful return the Map, or `None`
    */
  def getClaimAsMap(jwt: DecodedJWT, claim: String): Option[Map[String, AnyRef]] =
    Option(jwt.getClaim(claim))
    // `asMap` may return null or throw JWTDecodeException.
      .map(c => Either.catchNonFatal(Option(c.asMap)))
      .flatMap(_.toOption)
      .flatten
      .map(_.asScala.toMap)

  /**
    * Given a decoded JWT will return a partially applied function which can then receive the name
    * of a claim and return the value as a `String` or `None` if not present in the claims.
    *
    * @param jwt a token containing claims which will be wrapped in the returned function
    * @return a function which given the name of a claim will optionally return its value.
    */
  def getClaim(jwt: DecodedJWT): String => Option[String] =
    (claim: String) => getClaim(jwt, claim)
}
