name: Deployment Workflow
on:
  workflow_dispatch:
    # inputs:
    #   env:
    #     description: 'Env'
    #     required: false
      
jobs:
  job_staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    # if: github.event.inputs.env == 'staging'
    steps:
    - name: deploying HCL Enterprise Staging
      uses: appleboy/ssh-action@master
      with:
        password: ${{ secrets.STAGING_MACHINE_PASSWORD }}    # RAC private key from pem file
        host: ${{ secrets.STAGING_MACHINE_HOST }}            # ec2-13-235-61-252.ap-south-1.compute.amazonaws.com
        username: ${{ secrets.STAGING_MACHINE_USERNAME }}    # ubuntu
        port: 22
        script: sh /home/ubuntu/openEQUELLA/open_equella_script.sh